# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'MVVM-todo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Elegance App
  pod 'RealmSwift'
  pod 'RxDataSources', '~> 4.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxRealm'
  pod "RxGesture"
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase'
  pod 'Firebase/Analytics'
  #pod 'Firebase/Core'
  #pod 'Firebase/Messaging'
end
